Correção de header no Sicredi
BoletoNet/boleto2net pull request #318
Opened 2021-07-01 12:14 UTC by MatheusJordao

Correção de header conforme manual do Sicredi.

No arquivo estava "SICRED", alterei para "SICREDI" conforme consta no manual:

![image](https://user-images.githubusercontent.com/44534738/124122541-93626180-da4c-11eb-8d3c-6df1a5151832.png)

2021-07-01 12:32 UTC, MatheusJordao commented
O arquivo do Sicredi está montando o "Nosso número" fixando o número 2, tive problemas com isso pois o banco me informou que deveria informar o DV. 
Então estou declarando uma variável codigoDV = 2 para não alterar a estrutura atual, depois eu atualizo essa variável somente se foi informado o DV.

2021-07-01 13:31 UTC, rafd75 commented
> O arquivo do Sicredi está montando o "Nosso número" fixando o número 2, tive problemas com isso pois o banco me informou que deveria informar o DV.
> Então estou declarando uma variável codigoDV = 2 para não alterar a estrutura atual, depois eu atualizo essa variável somente se foi informado o DV.

@MatheusJordao bom dia... 

Se não me engano, o Sicredi, foi o único banco que eu não "portei" do BoletoNet para o Boleto2Net ... não me recordo quem implementou...

Mas eu sei que desde então, muitas issues apareceram aqui sobre esse banco.

Quanto ao nosso número, fixando "2", vi sua implementação e **se confirmar que no manual diz que é o códigoDV mesmo**, não tenho dúvidas de que o código deveria ser esse:

```
var DataDocumento = boleto.DataEmissao.ToString("yy");
var nossoNumero = boleto.NossoNumero;
var codigoDV = boleto.Banco.Cedente.CodigoDV;
boleto.NossoNumero = string.Format("{0}{1}{2}", DataDocumento, codigoDV, nossoNumero.PadLeft(5, '0'));
```

O dia que eu precisar usar o SICREDI aqui, vou repassar todo o manual, pq sinceramente, dado o número de issues, eu não confio totalmente de que esteja implementado do jeito certo.

Obs: Idem para os testes unitários dessa carteira... precisam ser validados, pq não posso garantir que os valores não "forçam" o teste ser válido...

@MatheusJordao  -  O que vc acha do que falei acima?

 ... @carloscds --- da uma opinião ai também...

2021-07-01 14:00 UTC, MatheusJordao commented
@rafd75 concordo com sua sugestão de código, mas tenho medo de fazê-la porque não sei se existe a possibilidade de carteiras antigas do Sicredi não utilizarem o DV.

2021-08-06 18:07 UTC, rafd75 requested changes
Olhei por cima as alterações mais significativas.
Fora isso, no Bradesco, todas as linhas com acento estão com diferença...

Tem muita alteração em campo com Juros entre Percentual e Valor... Precisa ser revisto isso com calma - No chute, se eu aplico esse ajuste aqui na minha versão, vai quebrar pq se não me engano, eu faço a conta entre percentual e valor, pelo aplicativo (e não na dll)...

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBrasil.cs
> +                    percJurosMensal = boleto.PercentualJurosDia * 30;
Esse tipo de tratativa, deve ser feita na aplicação, e não dentro da biblioteca

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBrasil.cs
> +                reg.Adicionar(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0038, 020, 0, boleto.NossoNumeroFormatado, ' ');
Qual a diferença, no BB, entre essas propriedades? ... Essa alteração pode quebrar as implementações existentes do Boleto2Net.

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBrasil.cs
> +                if (percJurosMensal == 0)
e como fica se estiver preenchido o Valor ao invés do percentual?

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBrasil.cs
> +                    reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0127, 015, 2, percJurosMensal, '0');
idem acima.

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBrasil.cs
> +                    codMulta = "2";
idem acima

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBrasil.cs
> +                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0075, 015, 2, boleto.PercentualMulta, '0');
idem acima

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoCaixa.cs
> +                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0018, 003, 0, "0", '0');
CEF eu tenho homologado aqui também...

Alteraram o layout lá?

2021-08-06 18:07 UTC, rafd75 commented on Boleto2.Net/Banco/BancoCaixa.cs
> +                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0021, 007, 0, "007", '0');
Ficou fixo 007 ?    ao invés do código do cedente?

2022-02-02 22:03 UTC, rafd75 commented
@MatheusJordao , boa noite... 

Como ficou esse Pull Request?
Você chegou a avaliar os pontos de atenção acima?

2022-11-09 19:27 UTC, rafd75 requested changes

2022-11-09 19:27 UTC, rafd75 commented on Boleto2.Net.Testes/Boleto2.Net.Testes.csproj
> +    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
Versão 4.8?

2022-11-09 19:27 UTC, rafd75 commented on Boleto2.Net/Banco/BancoBradesco.cs
> +                reg.Adicionar(TTiposDadoEDI.ediNumericoSemSeparador_, 0013, 007, 0, Empty, ' ');
Esses ajustes no Bradesco, tem alguma solicitação no manual? qual versão?

2022-12-29 17:29 UTC, carloscds commented
@MatheusJordao Seu PR esta com conflitos, poderia verificar ?

2022-12-29 17:38 UTC, closed without merging